version: "3.4"
services:
  order-api:
    container_name: order-api
    environment:
      ConnectionStrings__OrderContext: "Data Source=sql-server-database; Initial Catalog=Order; User Id=sa; Password=1StrongPassword*"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql-server-database
      - otel-collector
    command: "dotnet Order.Api.dll"
    ports:
      - "80:80"

  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    user: root
    environment:
      SA_PASSWORD: 1StrongPassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbit:
    image: rabbitmq:3.5
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=my_vhost
  
  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "--mem-ballast-size-mib=683" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tracing-tool
    ports:
      - "4317:4317"
    restart: always
  
  tracing-tool:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "4317:4317"
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    working_dir: /app
    environment:
      PATH: "$PATH:$HOME/:dotnet/tools/"
      API_PROJECT: Order.Api/Order.Api.csproj
      API_SQL_CONTEXT_CLASS: OrderContext
      CONSUMER_PROJECT: Catalog.Consumer/Catalog.Consumer.csproj
      CONSUMER_SQL_CONTEXT_CLASS: CatalogContext
      ConnectionStrings__OrderContext: "Data Source=sql-server-database; Initial Catalog=Order; User Id=sa; Password=1StrongPassword*"
      ConnectionStrings__CatalogContext: "Data Source=sql-server-database; Initial Catalog=Catalog; User Id=sa; Password=1StrongPassword*"
    command: "bash ./Scripts/apply-existing-migrations.sh"
    depends_on:
      - sql-server-database
